name: Build AAB

on:
 push:
   branches:
     - master

jobs:

 build:
   name: Build AAB
   runs-on: ubuntu-latest

   steps:
     - name: Checkout source
       uses: actions/checkout@v2

     - name: Setup java
       uses: actions/setup-java@v1
       with:
         distribution: 'zulu'
         java-version: '11'

     - name: Setup Node.js
       uses: actions/setup-node@v1
       with:
         node-version: 18.x

     - name: Install app dependencies
       run: npm install

     - name: Build app
       run: npm run build

     - name: Capacitor copy
       run: npx cap copy

     - name: Capacitor update
       run: npx cap update

     - name: Build app bundle
       run: cd android && gradle bundle

     - name: Extract Android signing key from env
       run: |
         echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
         base64 -d android/release.jks.base64 > android/release.decrypted.jks

     - name: Sign dev build
       run: jarsigner -keystore android/release.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab release

     - name: Upload release bundle
       uses: actions/upload-artifact@v4
       with:
         name: app-release
         path: android/app/build/outputs/bundle/release/app-release-signed.aab
         retention-days: 60

